# action.yml
name: 'GlassFlow Pipelines Push action'
description: 'This Github Action lets you automate GlassFlow pipelines deployments as code'
branding:
  icon: zap
  color: purple
inputs:
  pipelines-dir:
    description: |
      Path to directory with GlassFlow pipelines.
      Default 'pipelines'
    default: "pipelines"
  glassflow-personal-access-token:
    description: |
      GlassFlow personal access token to interact with API.
    required: true
  dry-run:
    description: Do not actually push any changes
    required: false
    default: "false"

outputs:
  to-create-count:
    description: Number of new pipelines to create
    value: ${{ steps.push-to-glassflow.outputs.to-create-count }}
  to-create-ids:
    description: Pipeline IDs that were created
    value: ${{ steps.push-to-glassflow.outputs.to-create-ids }}
  to-update-count:
    description: Number of pipelines to update
    value: ${{ steps.push-to-glassflow.outputs.to-update-count }}
  to-update-ids:
    description: Pipeline IDs that will be updated
    value: ${{ steps.push-to-glassflow.outputs.to-update-ids }}
  to-delete-count:
    description: Number of pipelines to delete
    value: ${{ steps.push-to-glassflow.outputs.to-delete-count }}
  to-delete-ids:
    description: Pipeline IDs that will be deleted
    value: ${{ steps.push-to-glassflow.outputs.to-delete-ids }}

runs:
  using: "composite"
  steps:
    - name: Get file changes
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        recover_deleted_files: 'true'
        recover_files: |
          ${{ inputs.pipelines-dir }}/**/*.{yaml,yml}
        files: |
          ${{ inputs.pipelines-dir }}/**/*.{py,yaml,yml}
          ${{ inputs.pipelines-dir }}/**/requirements.txt

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Setup
      shell: bash
      id: setup
      run: |
        VERSION=1
        TEMPDIR=/tmp/action-script/
        mkdir -p ${TEMPDIR}
        cd ${TEMPDIR}
        echo "tempdir=${TEMPDIR}" >> $GITHUB_OUTPUT
        
        echo "Downloading action script ..."
        wget "https://github.com/glassflow/pipelines-push-action/archive/refs/tags/v${VERSION}.tar.gz"
        tar -xzvf v${VERSION}.tar.gz
        cp pipelines-push-action-${VERSION}/script/* .
        
        echo "Installing python dependencies ..."
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Set script arguments
      id: set-arguments
      shell: bash
      run: |
        args="args=-t ${{ inputs.glassflow-personal-access-token }} --pipelines-dir ${{ inputs.pipelines-dir }}";
        if ${{ inputs.dry-run == 'true' }}; 
        then
          args+=" --dry-run";
        fi;
        if [ "${{ steps.changed-files.outputs.deleted_files }}" ];
        then
          args+=" --files-deleted ${{ steps.changed-files.outputs.deleted_files }}";
        fi;
        if [ "${{ steps.changed-files.outputs.all_changed_files }}" ];
        then
          args+=" --files-changed ${{ steps.changed-files.outputs.all_changed_files }}";
        fi;
        echo $args >> $GITHUB_OUTPUT

    - name: Run
      id: run
      shell: bash
      run: |
        python ${{ steps.setup.outputs.tempdir }}/main.py ${{ steps.set-arguments.outputs.args }}

    - name: Clean up
      id: clean-up
      shell: bash
      run: rm -rf ${{ steps.setup.outputs.tempdir }}
          
    - name: Commit new Pipeline IDs
      if: ${{ (inputs.dry-run == 'false') && steps.run.outputs.to-create-ids }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply automatic changes (add new pipeline IDs)