# action.yml
name: 'GlassFlow Pipelines Push action'
description: 'This Github Action lets you automate GlassFlow pipelines deployments as code'
branding:
  icon: zap
  color: purple
inputs:
  pipelines-dir:
    description: |
      Path to directory with GlassFlow pipelines.
      Default 'pipelines/'
    default: "pipelines/"
  glassflow-personal-access-token:
    description: |
      GlassFlow personal access token to interact with API.
    required: true
  dry-run:
    description: Do not actually push any changes
    required: false
    default: "false"

outputs:
  to-create-count:
    description: Number of new pipelines to create
    value: ${{ steps.push-to-glassflow.outputs.to-create-count }}
  to-update-count:
    description: Number of pipelines to update
    value: ${{ steps.push-to-glassflow.outputs.to-update-count }}
  to-update-ids:
    description: Pipeline IDs that will be updated
    value: ${{ steps.push-to-glassflow.outputs.to-update-ids }}
  to-delete-count:
    description: Number of pipelines to delete
    value: ${{ steps.push-to-glassflow.outputs.to-delete-count }}
  to-delete-ids:
    description: Pipeline IDs that will be deleted
    value: ${{ steps.push-to-glassflow.outputs.to-delete-ids }}

runs:
  using: "composite"
  steps:
    - name: Get file changes
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          ${{ inputs.pipelines-dir }}/**/*.{py,yaml,yml}
          ${{ inputs.pipelines-dir }}/**/requirements.txt

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Download script and install dependencies
      shell: bash
      run: |
        wget https://gfscripts.fra1.cdn.digitaloceanspaces.com/pipelines-push-action-script/glassflow-pipeline-push-v1.tar.gz
        tar -xzvf glassflow-pipeline-push-v1.tar.gz
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Set script arguments
      id: set-arguments
      shell: bash
      run: |
        args="args=-t ${{ inputs.glassflow-personal-access-token }} --pipelines-dir ${{ inputs.pipelines-dir }}";
        if [ ${{ inputs.dry-run == 'true' }} ]; 
        then
          args+=" --dry-run";
        fi;
        if [ ${{ steps.changed-files.outputs.deleted_files }} ];
        then
          args+=" --files-deleted ${{ steps.changed-files.outputs.deleted_files }}";
        fi;
        if [ ${{ steps.changed-files.outputs.all_changed_files }} ];
        then
          args+=" --files-changed ${{ steps.changed-files.outputs.all_changed_files }}";
        fi;
        echo $args >> $GITHUB_OUTPUT

    - name: Run script to push pipelines
      id: push-to-glassflow
      shell: bash
      run: |
        python main.py ${{ steps.set-arguments.outputs.args }}
          
    - name: Commit new Pipeline IDs
      if: ${{ inputs.dry-run == 'false' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply automatic changes (add new pipeline IDs)
