# Example pipeline for testing action
name: Example pipeline
space_id: dbc98f33-805e-44ff-a5bd-8ee68052f43d

components:
  - id: source
    name: Source
    type: source

  - id: main
    name: Main
    type: transformer
    inputs:
      - source
    requirements:
      path: requirements.txt
    transformation:
      path: handler.py
    env_vars:
      - name: TEST_VARIABLE
        value: test value
      - name: TEST_SECRET
        value: test_secret

  - id: sink
    name: Sink
    type: sink
    inputs:
      - main
