name: Test
on:
  pull_request:

jobs:
  code-test:
    name: Code Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: 'pip'

      - name: Install
        shell: bash
        run: pip install -e .[tests]

      - name: pytest
        shell: bash
        run: pytest

  action-test:
    name: Github Action Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          glassflow-personal-access-token: ${{ secrets.GlassFlowPAT }}
          dry-run: 'true'
          pipelines-dir: "tests/data"
          sha: ${{ github.sha }}

      - name: Print Output
        id: output
        run: |
          echo "Pipelines to Create: ${{ steps.test-action.outputs.to-create-count }}"
          echo "Pipelines to Update: ${{ steps.test-action.outputs.to-update-count }}"
          echo "Pipelines to Delete: ${{ steps.test-action.outputs.to-delete-count }}"