name: Test
on:
  pull_request:

jobs:
  code-test:
    name: Code Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install
        shell: bash
        run: uv sync --all-extras --dev

      - name: pytest
        shell: bash
        run: uv run pytest

  action-test:
    name: Github Action Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          glassflow-personal-access-token: ${{ secrets.GlassFlowPAT }}
          dry-run: 'true'
          pipelines-dir: "tests/data"
          sha: ${{ github.sha }}

      - name: Print Output
        id: output
        run: |
          echo "Pipelines to Create: ${{ steps.test-action.outputs.to-create-count }}"
          echo "Pipelines to Update: ${{ steps.test-action.outputs.to-update-count }}"
          echo "Pipelines to Delete: ${{ steps.test-action.outputs.to-delete-count }}"